Запарсить итоговый датасет через Api у нас получилось 4 отдельными блоками данных. Поэтому их нужно сначала объединить

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dfs = [pd.read_csv('../datasets/superjob_vacancies.csv'), pd.read_csv('../datasets/superjob_vacancies_part_2.csv'), pd.read_csv('../datasets/superjob_vacancies_moscow_part1.csv'), pd.read_csv('../datasets/superjob_vacancies_moscow_part2.csv')]

In [4]:
df_sj = pd.concat(dfs, ignore_index=True)
df_sj

,id,Название вакансии,Минимальная зарплата,Максимальная зарплата,Валюта,Категория,Детальные категории,Город,Метро,Линия метро,...,Индуcтрия,Кол-во персонала в компании,Кол-во размещенных вакансий,Название компании,Опыт,График работы,Образование,Широта,Долгота,ссылка
0,31948884,Системный администратор,65000,0,rub,"['IT, Интернет, связь, телеком']","['Системное администрирование', 'Техническая п...",Санкт-Петербург,"['Петроградская', 'Чёрная Речка']","['Московско-Петроградская', 'Московско-Петрогр...",...,NaN,50 — 100,8.0,Санкт-Петербургский морской рыбопромышленный к...,От 1 года,Полный рабочий день,Не имеет значения,59.980118,30.279800,https://spb.superjob.ru/vakansii/sistemnyj-adm...
1,50742146,Администратор магазина,94900,113900,rub,"['Промышленность, производство', 'IT, Интернет...","['Промышленное оборудование', 'Внедрение и соп...",Санкт-Петербург,[],[],...,NaN,более 5000,49868.0,Пятёрочка,От 1 года,Полный рабочий день,Не имеет значения,59.903267,30.465429,https://spb.superjob.ru/vakansii/administrator...
2,46781727,Системный администратор,45000,0,rub,"['IT, Интернет, связь, телеком']","['Сетевые технологии', 'Системное администриро...",Санкт-Петербург,"['Невский Проспект', 'Гостиный Двор', 'Василео...","['Московско-Петроградская', 'Невско-Василеостр...",...,NaN,менее 50,2.0,Государственная библиотека,От 6 лет,Полный рабочий день,Высшее,59.938953,30.315643,https://spb.superjob.ru/vakansii/sistemnyj-adm...
3,51673017,Инженер по АСУ ТП (ТЭЦ-21),95526,95526,rub,"['IT, Интернет, связь, телеком', 'Промышленнос...","['Инжиниринг', 'Промышленное оборудование']",Санкт-Петербург,"['Гражданский Проспект', 'Девяткино', 'Проспек...","['Кировско-Выборгская', 'Кировско-Выборгская',...",...,NaN,более 5000,60.0,Территориальная генерирующая компания №1,От 1 года,Полный рабочий день,Не имеет значения,60.057323,30.476370,https://spb.superjob.ru/vakansii/inzhener-po-a...
4,51729020,Инженер 1 категории (отдел по работе с обращен...,75000,0,rub,"['Административная работа, секретариат, АХО', ...","['Делопроизводство', 'Диспетчерская служба', '...",Санкт-Петербург,[],[],...,NaN,500 — 1000,0.0,Жилищное агентство Красногвардейского района С...,От 1 года,Полный рабочий день,Среднее специальное,59.949829,30.412159,https://spb.superjob.ru/vakansii/inzhener-1-ka...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4509,51700816,"Продавец, кассир в магазин",68000,75000,rub,"['Спорт, фитнес, салоны красоты, SPA', 'Услуги...","['Фитнес-клубы / Спортзалы', 'Психологическое ...",Москва,[],[],...,NaN,более 5000,3198.0,"""БЭСТ ПРАЙС"" / Fix Price",Без опыта,Полный рабочий день,Не имеет значения,55.732788,37.711067,https://www.superjob.ru/vakansii/prodavec-5170...
4510,51773032,Уборщик (м. Проспект мира),0,26400,rub,"['Услуги, ремонт, сервисное обслуживание']",['Клининг'],Москва,['Проспект Мира'],['Калужско-Рижская'],...,NaN,более 5000,236.0,"КуулКлевер (МясновЪ, Отдохни)",Без опыта,Полный рабочий день,Не имеет значения,55.786041,37.635845,https://www.superjob.ru/vakansii/uborschik-517...
4511,51773038,Уборщик (м. Медведково),0,33000,rub,"['Услуги, ремонт, сервисное обслуживание']",['Клининг'],Москва,['Медведково'],['Калужско-Рижская'],...,NaN,более 5000,236.0,"КуулКлевер (МясновЪ, Отдохни)",Без опыта,Полный рабочий день,Не имеет значения,55.882969,37.638908,https://www.superjob.ru/vakansii/uborschik-517...
4512,51809511,Уборщица,0,30000,rub,"['Услуги, ремонт, сервисное обслуживание']",['Клининг'],Москва,"['Волгоградский проспект', 'Дубровка']","['Таганско-Краснопресненская', 'МЦК']",...,NaN,менее 50,340.0,Jobers,Без опыта,Частичная занятость / Совместительство,Не имеет значения,55.722275,37.678226,https://www.superjob.ru/vakansii/uborschica-51...
4513,51780646,Санитарка-уборщица,65000,0,rub,"['Медицина, фармацевтика, ветеринария', 'Услуг...","['Другое', 'Клининг', 'Рабочий персонал, разное']",Москва,"['Юго-Западная', 'Коньково', 'Университет Друж...","['Сокольническая', 'Калужско-Рижская', 'Троицк...",...,NaN,1000 — 5000,46.0,"ФГБУ ""НМИЦ AГП им. В. И. Кулакова"" Минздрава Р...",Без опыта,Полный рабочий день,Не имеет значения,55.644421,37.500191,https://www.superjob.ru/vakansii/sanitarka-ubo...

In [11]:
df_sj.to_csv('../datasets/superjob_all.csv', index=False)

Из-за такого сбора данных могло получится много дубликатов. Посмотрим на них:

In [6]:
df_sj[df_sj.duplicated(keep='first')]

,id,Название вакансии,Минимальная зарплата,Максимальная зарплата,Валюта,Категория,Детальные категории,Город,Метро,Линия метро,...,Индуcтрия,Кол-во персонала в компании,Кол-во размещенных вакансий,Название компании,Опыт,График работы,Образование,Широта,Долгота,ссылка
93,37047811,Инженер-программист АСУ ТП / Программист промы...,120000,160000,rub,"['IT, Интернет, связь, телеком', 'Промышленнос...","['Инжиниринг', 'Разработка, программирование',...",Санкт-Петербург,"['Площадь Александра Невского 1', 'Площадь Але...","['Невско-Василеостровская', 'Правобережная']",...,NaN,менее 50,1375.0,ВЕРТЕК,От 3 лет,Полный рабочий день,Высшее,59.914280,30.396284,https://spb.superjob.ru/vakansii/inzhener-prog...
185,51810383,Инженер-электроник 1 категории,0,95000,rub,"['IT, Интернет, связь, телеком', 'Промышленнос...","['Инжиниринг', 'Радиотехническая и электронная...",Санкт-Петербург,"['Площадь Ленина', 'Выборгская', 'Горьковская'...","['Кировско-Выборгская', 'Кировско-Выборгская',...",...,NaN,более 5000,126.0,"СПб ГУП ""Горэлектротранс""",От 3 лет,Полный рабочий день,Не имеет значения,59.960075,30.325993,https://spb.superjob.ru/vakansii/inzhener-elek...
273,51868056,Инженер-электроник 1 категории,0,95000,rub,"['IT, Интернет, связь, телеком', 'Промышленнос...","['Инжиниринг', 'Радиотехническая и электронная...",Санкт-Петербург,[],[],...,NaN,более 5000,126.0,"СПб ГУП ""Горэлектротранс""",От 3 лет,Полный рабочий день,Не имеет значения,59.862606,30.471645,https://spb.superjob.ru/vakansii/inzhener-elek...
400,50742146,Администратор магазина,94900,113900,rub,"['Промышленность, производство', 'IT, Интернет...","['Промышленное оборудование', 'Внедрение и соп...",Санкт-Петербург,[],[],...,NaN,более 5000,49868.0,Пятёрочка,От 1 года,Полный рабочий день,Не имеет значения,59.903267,30.465429,https://spb.superjob.ru/vakansii/administrator...
461,51794152,Инженер-электроник 3 категории,0,65170,rub,"['IT, Интернет, связь, телеком', 'Промышленнос...","['Инжиниринг', 'Радиотехническая и электронная...",Санкт-Петербург,[],[],...,NaN,менее 50,337.0,JOBCART.RU,От 1 года,Полный рабочий день,Не имеет значения,59.954781,30.256733,https://spb.superjob.ru/vakansii/inzhener-elek...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4474,50895660,Столяр 6 разряда,84000,84000,rub,"['Промышленность, производство', 'Рабочий перс...","['Мебельное производство', 'Квалифицированный ...",Москва,['Курская'],['МЦД4'],...,NaN,1000 — 5000,36.0,МОСГАЗ,От 1 года,Полный рабочий день,Не имеет значения,55.757450,37.667419,https://www.superjob.ru/vakansii/stolyar-6-raz...
4475,51225926,Инженер-электрик,0,0,rub,"['Строительство, проектирование, недвижимость']",['Электроснабжение'],Москва,[],[],...,NaN,более 5000,37.0,ЦЕМРОС,От 3 лет,Полный рабочий день,Не имеет значения,NaN,NaN,https://www.superjob.ru/vakansii/inzhener-elek...
4476,51578076,Сервисный инженер по эксплуатации систем конди...,124000,124000,rub,"['Строительство, проектирование, недвижимость'...","['Эксплуатация зданий', 'Автомобильная промышл...",Москва,['Парк Культуры'],['Кольцевая'],...,NaN,1000 — 5000,9.0,RT,От 1 года,Полный рабочий день,Среднее специальное,55.737358,37.590496,https://www.superjob.ru/vakansii/servisnyj-inz...
4477,51619130,Слесарь-сантехник,80000,80000,rub,"['Строительство, проектирование, недвижимость'...","['Водоснабжение, канализация', 'Рабочий персон...",Москва,[],[],...,NaN,1000 — 5000,3.0,ФИАН,От 1 года,Полный рабочий день,Не имеет значения,55.461357,37.294483,https://www.superjob.ru/vakansii/slesar-santeh...
4504,49733931,Инженер по транспорту,70000,0,rub,"['Промышленность, производство', 'Услуги, ремо...","['Автомобильная промышленность', 'Железнодорож...",Москва,"['Аннино', 'Бульвар Дмитрия Донского']","['Серпуховско-Тимирязевская', 'Серпуховско-Тим...",...,NaN,1000 — 5000,8914.0,«Группа ГУТА»,От 1 года,Полный рабочий день,Не имеет значения,55.587860,37.623341,https://www.superjob.ru/vakansii/inzhener-po-t...

In [15]:
df_sj = df_sj.drop_duplicates()
df_sj

,id,Название вакансии,Минимальная зарплата,Максимальная зарплата,Валюта,Категория,Детальные категории,Город,Метро,Линия метро,...,Индуcтрия,Кол-во персонала в компании,Кол-во размещенных вакансий,Название компании,Опыт,График работы,Образование,Широта,Долгота,ссылка
0,31948884,Системный администратор,65000,0,rub,"['IT, Интернет, связь, телеком']","['Системное администрирование', 'Техническая п...",Санкт-Петербург,"['Петроградская', 'Чёрная Речка']","['Московско-Петроградская', 'Московско-Петрогр...",...,NaN,50 — 100,8.0,Санкт-Петербургский морской рыбопромышленный к...,От 1 года,Полный рабочий день,Не имеет значения,59.980118,30.279800,https://spb.superjob.ru/vakansii/sistemnyj-adm...
1,50742146,Администратор магазина,94900,113900,rub,"['Промышленность, производство', 'IT, Интернет...","['Промышленное оборудование', 'Внедрение и соп...",Санкт-Петербург,[],[],...,NaN,более 5000,49868.0,Пятёрочка,От 1 года,Полный рабочий день,Не имеет значения,59.903267,30.465429,https://spb.superjob.ru/vakansii/administrator...
2,46781727,Системный администратор,45000,0,rub,"['IT, Интернет, связь, телеком']","['Сетевые технологии', 'Системное администриро...",Санкт-Петербург,"['Невский Проспект', 'Гостиный Двор', 'Василео...","['Московско-Петроградская', 'Невско-Василеостр...",...,NaN,менее 50,2.0,Государственная библиотека,От 6 лет,Полный рабочий день,Высшее,59.938953,30.315643,https://spb.superjob.ru/vakansii/sistemnyj-adm...
3,51673017,Инженер по АСУ ТП (ТЭЦ-21),95526,95526,rub,"['IT, Интернет, связь, телеком', 'Промышленнос...","['Инжиниринг', 'Промышленное оборудование']",Санкт-Петербург,"['Гражданский Проспект', 'Девяткино', 'Проспек...","['Кировско-Выборгская', 'Кировско-Выборгская',...",...,NaN,более 5000,60.0,Территориальная генерирующая компания №1,От 1 года,Полный рабочий день,Не имеет значения,60.057323,30.476370,https://spb.superjob.ru/vakansii/inzhener-po-a...
4,51729020,Инженер 1 категории (отдел по работе с обращен...,75000,0,rub,"['Административная работа, секретариат, АХО', ...","['Делопроизводство', 'Диспетчерская служба', '...",Санкт-Петербург,[],[],...,NaN,500 — 1000,0.0,Жилищное агентство Красногвардейского района С...,От 1 года,Полный рабочий день,Среднее специальное,59.949829,30.412159,https://spb.superjob.ru/vakansii/inzhener-1-ka...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4509,51700816,"Продавец, кассир в магазин",68000,75000,rub,"['Спорт, фитнес, салоны красоты, SPA', 'Услуги...","['Фитнес-клубы / Спортзалы', 'Психологическое ...",Москва,[],[],...,NaN,более 5000,3198.0,"""БЭСТ ПРАЙС"" / Fix Price",Без опыта,Полный рабочий день,Не имеет значения,55.732788,37.711067,https://www.superjob.ru/vakansii/prodavec-5170...
4510,51773032,Уборщик (м. Проспект мира),0,26400,rub,"['Услуги, ремонт, сервисное обслуживание']",['Клининг'],Москва,['Проспект Мира'],['Калужско-Рижская'],...,NaN,более 5000,236.0,"КуулКлевер (МясновЪ, Отдохни)",Без опыта,Полный рабочий день,Не имеет значения,55.786041,37.635845,https://www.superjob.ru/vakansii/uborschik-517...
4511,51773038,Уборщик (м. Медведково),0,33000,rub,"['Услуги, ремонт, сервисное обслуживание']",['Клининг'],Москва,['Медведково'],['Калужско-Рижская'],...,NaN,более 5000,236.0,"КуулКлевер (МясновЪ, Отдохни)",Без опыта,Полный рабочий день,Не имеет значения,55.882969,37.638908,https://www.superjob.ru/vakansii/uborschik-517...
4512,51809511,Уборщица,0,30000,rub,"['Услуги, ремонт, сервисное обслуживание']",['Клининг'],Москва,"['Волгоградский проспект', 'Дубровка']","['Таганско-Краснопресненская', 'МЦК']",...,NaN,менее 50,340.0,Jobers,Без опыта,Частичная занятость / Совместительство,Не имеет значения,55.722275,37.678226,https://www.superjob.ru/vakansii/uborschica-51...
4513,51780646,Санитарка-уборщица,65000,0,rub,"['Медицина, фармацевтика, ветеринария', 'Услуг...","['Другое', 'Клининг', 'Рабочий персонал, разное']",Москва,"['Юго-Западная', 'Коньково', 'Университет Друж...","['Сокольническая', 'Калужско-Рижская', 'Троицк...",...,NaN,1000 — 5000,46.0,"ФГБУ ""НМИЦ AГП им. В. И. Кулакова"" Минздрава Р...",Без опыта,Полный рабочий день,Не имеет значения,55.644421,37.500191,https://www.superjob.ru/vakansii/sanitarka-ubo...